-- Stage4-D Gate2-B: runtime WRITE schema preparation (role, grants, RLS, identity columns).
--
-- APPLIED LIVE 2026-10-07 to project hwdvyhunozporfuefteb (clinic-lead-shadow) as part of
-- Stage4-D "Live Gate 1" (see docs/supabase_migration/26_stage4d_live_gate1_ddl_apply.md for the
-- full catalog verification, Security Advisor before/after, and the sequence-grant scope fix
-- applied in the same session -- see stage4d_scope_fix_revoke_out_of_scope_sequence_grants.sql).
-- The sequence-grant loop below reflects that fix (explicit 7-sequence list), so re-running this
-- exact file against a fresh environment will not repeat the original scope issue.
--
-- Safe-by-construction properties:
--   * Every statement is idempotent (IF NOT EXISTS / DO $$ catalog checks) -- safe to re-run.
--   * No DROP, no TRUNCATE, no UPDATE/DELETE of existing rows, no PK/UUID/medical_key rewrite.
--   * Identity start values are computed from live MAX(id), never hardcoded over existing data.
--   * clinic_runtime gets only SELECT/INSERT/UPDATE/DELETE on the Gate1.5 mandatory (A+B) tables
--     and USAGE on the sequences it needs -- never DDL, never BYPASSRLS, never schema ownership.
--   * No grant of any kind to anon, authenticated, or PUBLIC.
--
-- Run inside one transaction (psql default) so a mid-script failure leaves nothing applied.

begin;

-- =========================================================================================
-- 1. Owner Decision 2: reserved high-range identity for the two tables whose generated id is
--    captured and reused in-flight by application code (store.py:396,402,694). Floor and
--    rationale: docs/supabase_migration/22_stage4d_write_inventory_gate.md "Owner Decision 2".
-- =========================================================================================

do $$
declare
  reserved_floor bigint := 1000000000;
  start_value bigint;
begin
  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'clinics' and a.attname = 'id' and a.attidentity <> ''
  ) then
    select greatest(reserved_floor, coalesce(max(id), 0) + 1) into start_value from public.clinics;
    execute format('alter table public.clinics alter column id add generated by default as identity (start with %s)', start_value);
  end if;

  if not exists (
    select 1 from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'provenance' and c.relname = 'source_records' and a.attname = 'id' and a.attidentity <> ''
  ) then
    select greatest(reserved_floor, coalesce(max(id), 0) + 1) into start_value from provenance.source_records;
    execute format('alter table provenance.source_records alter column id add generated by default as identity (start with %s)', start_value);
  end if;
end $$;

-- =========================================================================================
-- 2. Ordinary (non-reserved-range) identity for the other bigint-PK tables that insert new
--    rows without the application ever reading back/reusing the generated value (residual
--    note in the Gate 1.5 doc: these still need SOME generation mechanism, but not the
--    collision-avoidance floor, since no in-flight correctness depends on their specific id).
-- =========================================================================================

do $$
declare
  t record;
  start_value bigint;
begin
  for t in
    select * from (values
      ('provenance', 'change_history'),
      ('provenance', 'match_reviews'),
      ('provenance', 'comdesk_original_rows'),
      ('provenance', 'google_maps_results'),
      ('research',   'search_usage')
    ) as x(schema_name, table_name)
  loop
    if not exists (
      select 1 from pg_attribute a
      join pg_class c on c.oid = a.attrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = t.schema_name and c.relname = t.table_name and a.attname = 'id' and a.attidentity <> ''
    ) then
      execute format('select coalesce(max(id),0)+1 from %I.%I', t.schema_name, t.table_name) into start_value;
      execute format('alter table %I.%I alter column id add generated by default as identity (start with %s)',
                      t.schema_name, t.table_name, start_value);
    end if;
  end loop;
end $$;

-- =========================================================================================
-- 3. Runtime least-privilege role. Never SUPERUSER/BYPASSRLS/CREATEDB/CREATEROLE/ownership.
--    CREATE ROLE has no IF NOT EXISTS in PostgreSQL -- guard via pg_roles catalog check.
-- =========================================================================================

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'clinic_runtime') then
    create role clinic_runtime with login nosuperuser nocreatedb nocreaterole nobypassrls noinherit;
  end if;
end $$;

-- A connection-level statement_timeout keeps a stuck runtime statement from holding a
-- long-lived lock; mirrors the existing READ-side pattern in src/repository/supabase_pool.py.
alter role clinic_runtime set statement_timeout = '15s';

grant usage on schema public, provenance, research, app_config, treatment, hp_research to clinic_runtime;

-- Mandatory (Gate1.5 Class A+B) tables only -- never a schema-wide "ALL TABLES" grant, so a
-- future new table in these schemas does NOT silently become writable by clinic_runtime.
grant select, insert, update on public.clinics to clinic_runtime;
grant select, insert on provenance.templates to clinic_runtime;
grant select, insert, update on provenance.source_records to clinic_runtime;
grant select, insert on provenance.import_batches to clinic_runtime;
grant select, insert on provenance.change_history to clinic_runtime;              -- append-only audit: no update/delete
grant select, insert, update on provenance.comdesk_original_rows to clinic_runtime;
grant select, insert on provenance.google_maps_results to clinic_runtime;
grant select, insert, update on provenance.match_reviews to clinic_runtime;
grant select, insert, update, delete on provenance.manual_overrides to clinic_runtime;  -- override(value=None) deletes
grant select, insert, update on research.research_jobs to clinic_runtime;
grant select, insert, update on research.research_job_items to clinic_runtime;
grant select, insert, update on research.research_results to clinic_runtime;
grant select, insert, update, delete on research.hp_pages to clinic_runtime;      -- save_research replaces the full page set
grant select, insert on research.search_usage to clinic_runtime;
grant select, insert, update on research.search_cache to clinic_runtime;
grant select, insert, update on app_config.settings to clinic_runtime;
grant select, insert, update, delete on treatment.clinic_research_status to clinic_runtime;
grant select, insert, update, delete on treatment.clinic_treatment_research to clinic_runtime;  -- worker replaces per-clinic set
grant select, insert, update on hp_research.clinic_hp_research to clinic_runtime;

-- Sequence USAGE for the identity columns created above (identity sequences are owned by the
-- column and granted via the table grant automatically for GENERATED ... AS IDENTITY in PG10+,
-- but USAGE is granted explicitly here for clarity/portability).
--
-- Scoped to exactly the 7 sequences this migration creates/owns -- NOT "every sequence in
-- public/provenance/research" (an earlier version of this migration did that and, on first
-- live apply, it also granted USAGE on 4 pre-existing sequences belonging to out-of-scope
-- tables -- clinic_email_enrichment, new_clinic_candidates, new_clinic_candidate_evidence,
-- new_clinic_source_records -- that have no corresponding table GRANT or RLS policy for
-- clinic_runtime and were never meant to be touched. Caught and revoked the same session;
-- see stage4d_scope_fix_revoke_out_of_scope_sequence_grants.sql for the exact corrective SQL
-- that was run live. This explicit list is the fix, so a fresh apply never repeats it.
do $$
declare
  seq record;
begin
  for seq in
    select * from (values
      ('public', 'clinics'), ('provenance', 'source_records'), ('provenance', 'change_history'),
      ('provenance', 'match_reviews'), ('provenance', 'comdesk_original_rows'),
      ('provenance', 'google_maps_results'), ('research', 'search_usage')
    ) as x(schema_name, table_name)
  loop
    -- Default PostgreSQL identity-sequence naming: <table>_<column>_seq, column is always "id"
    -- for every one of these 7 tables -- confirmed against the live catalog after first apply.
    if exists (
      select 1 from pg_sequences
      where schemaname = seq.schema_name and sequencename = seq.table_name || '_id_seq'
    ) then
      execute format('grant usage, select on sequence %I.%I to clinic_runtime',
                      seq.schema_name, seq.table_name || '_id_seq');
    end if;
  end loop;
end $$;

-- Explicitly no grants to anon, authenticated, or PUBLIC on any of the above -- the existing
-- Security Advisor baseline (ERROR 0 / WARNING 0) must not regress. These REVOKEs are no-ops if
-- nothing was ever granted; they exist to make absence of client-role write access verifiable
-- by reading this file, not by trusting an unstated default.
revoke all on public.clinics, provenance.templates, provenance.source_records, provenance.import_batches,
  provenance.change_history, provenance.comdesk_original_rows, provenance.google_maps_results,
  provenance.match_reviews, provenance.manual_overrides, research.research_jobs, research.research_job_items,
  research.research_results, research.hp_pages, research.search_usage, research.search_cache,
  app_config.settings, treatment.clinic_research_status, treatment.clinic_treatment_research,
  hp_research.clinic_hp_research
from anon, authenticated, public;

-- =========================================================================================
-- 4. RLS policies for clinic_runtime only. All 19 target tables already have RLS enabled with
--    zero policies (confirmed live, see docs/supabase_migration/22_stage4d_write_inventory_gate.md
--    independent verification addendum) -- so with RLS enabled and no policy, clinic_runtime
--    currently could SELECT/INSERT/UPDATE/DELETE nothing despite the GRANTs above. These
--    policies grant exactly what the GRANTs already allow, `TO clinic_runtime` only -- never a
--    permissive `USING (true)` applied to PUBLIC/anon/authenticated.
-- =========================================================================================

do $$
declare
  t record;
begin
  for t in
    select * from (values
      ('public','clinics'), ('provenance','templates'), ('provenance','source_records'),
      ('provenance','import_batches'), ('provenance','change_history'),
      ('provenance','comdesk_original_rows'), ('provenance','google_maps_results'),
      ('provenance','match_reviews'), ('provenance','manual_overrides'),
      ('research','research_jobs'), ('research','research_job_items'),
      ('research','research_results'), ('research','hp_pages'), ('research','search_usage'),
      ('research','search_cache'), ('app_config','settings'),
      ('treatment','clinic_research_status'), ('treatment','clinic_treatment_research'),
      ('hp_research','clinic_hp_research')
    ) as x(schema_name, table_name)
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = t.schema_name and tablename = t.table_name and policyname = 'clinic_runtime_rw'
    ) then
      execute format(
        'create policy clinic_runtime_rw on %I.%I for all to clinic_runtime using (true) with check (true)',
        t.schema_name, t.table_name
      );
    end if;
  end loop;
end $$;

commit;

-- =========================================================================================
-- Post-apply validation (run manually, read-only, immediately after commit -- see
-- docs/supabase_migration/23_stage4d_gate2_offline_preparation.md "DDL適用後Validation"):
--
--   select min(id) from public.clinics where id >= 1000000000;             -- expect: no rows yet
--   select last_value from pg_sequences where schemaname='public' and sequencename like '%clinics%';
--   select rolname, rolsuper, rolbypassrls, rolcreatedb, rolcreaterole from pg_roles where rolname='clinic_runtime';
--   select * from pg_policies where schemaname in (...) and policyname='clinic_runtime_rw';
--   select grantee, table_schema, table_name, privilege_type from information_schema.table_privileges
--     where grantee in ('anon','authenticated','PUBLIC') and table_schema in (...);  -- expect: 0 rows
--   select count(*) from public.clinics;                                   -- expect: 162258, unchanged
-- =========================================================================================
